"""add mechanism to flavor pairings

Revision ID: 348f3be13a23
Revises: 66d9aee12040
Create Date: 2026-10-10 11:39:58.776410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348f3be13a23'
down_revision: Union[str, Sequence[str], None] = '66d9aee12040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavor_pairings', sa.Column('mechanism', sa.String(length=30), server_default='molecular_harmony', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flavor_pairings', 'mechanism')
    # ### end Alembic commands ###
