"""001_initial_schema

Revision ID: 66d9aee12040
Revises:
Create Date: 2026-10-05 20:54:19.452499

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "66d9aee12040"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("color_code", sa.String(length=7), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "favorite_combinations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("ingredient_key", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "ingredient_key", name="uq_user_combination"),
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "flavor_profile",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "favorite_combination_items",
        sa.Column("combination_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["combination_id"], ["favorite_combinations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"], ["ingredients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("combination_id", "ingredient_id"),
    )
    op.create_table(
        "flavor_pairings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ingredient_a_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_b_id", sa.Integer(), nullable=False),
        sa.Column("affinity_score", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("ai_rationale", sa.String(length=300), nullable=True),
        sa.Column(
            "source_type",
            sa.String(length=30),
            server_default="llm_synthesis",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "affinity_score >= 0.00 AND affinity_score <= 1.00", name="chk_score_range"
        ),
        sa.CheckConstraint(
            "ai_rationale IS NULL OR length(ai_rationale) <= 300",
            name="chk_rationale_len",
        ),
        sa.CheckConstraint(
            "ingredient_a_id < ingredient_b_id", name="chk_ordered_pair"
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_a_id"], ["ingredients.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_b_id"], ["ingredients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ingredient_a_id", "ingredient_b_id", name="uq_ingredient_pair"
        ),
    )
    op.create_index(
        "idx_pairings_b", "flavor_pairings", ["ingredient_b_id"], unique=False
    )
    op.create_index(
        "idx_pairings_score",
        "flavor_pairings",
        [sa.literal_column("affinity_score DESC")],
        unique=False,
    )
    op.create_table(
        "pairing_review_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ingredient_a_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_b_id", sa.Integer(), nullable=False),
        sa.Column("suggested_score", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("ai_rationale", sa.String(length=300), nullable=True),
        sa.Column("flag_reason", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="pending_review",
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending_review', 'approved', 'rejected')",
            name="chk_review_status",
        ),
        sa.CheckConstraint(
            "ingredient_a_id < ingredient_b_id", name="chk_review_ordered_pair"
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_a_id"], ["ingredients.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_b_id"], ["ingredients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_review_queue_status", "pairing_review_queue", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_review_queue_status", table_name="pairing_review_queue")
    op.drop_table("pairing_review_queue")
    op.drop_index("idx_pairings_score", table_name="flavor_pairings")
    op.drop_index("idx_pairings_b", table_name="flavor_pairings")
    op.drop_table("flavor_pairings")
    op.drop_table("favorite_combination_items")
    op.drop_table("ingredients")
    op.drop_table("favorite_combinations")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("categories")
    # ### end Alembic commands ###
